### ISSUE TITLE
Form posts missing the word "post"

### ISSUE THREAD

**Issue by cobaltt7** [mxmou/exactcount#1]
I used the version of this availibe in Scratch Addons, and it is missing the word "posts" next to the exact count of form posts. Here is an example: https://tinyurl.com/yy7szxyy

**Comment by cobaltt7** [comment]
Does this go here, or in Scratch Addons?

**Comment by mxmou** [comment]
This issue should be in Scratch Addons.

**Comment by mxmou** [comment]
See ScratchAddons/ScratchAddons#731
